
name: Compile and push PDF File
# run-name: Compile and push PDF File     !outdated
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      
      - name: System
        run: |
          echo "User: ${{ github.actor }}"
          echo "Trigger: ${{ github.event_name }}"
          echo "OS: ${{ runner.os }}"
          echo "Branch: ${{ github.repository }}:${{ github.ref }}"
           
      - name: Build Latex
       # uses: xu-cheng/latex-action@v2
        run: |
          sudo apt update -y
          sudo apt upgrade -y
          sudo apt install -y texlive-base
          sudo apt install -y texlive-latex-extra 
          sudo apt install -y texlive-full
          sudo apt install -y latexmk 
          sudo apt install -y biber 
          sudo apt install -y texlive-binaries
          sudo apt update -y
          sudo apt upgrade -y

      - name: Compile Latex
        run: |
          cd ./Mathematik
          pdflatex main.tex
          makeindex main.idx -s StyleInd.ist
          biber main.tex
          pdflatex main.tex
          pdflatex main.tex

      - name: Rename PDF
        run: |
          mv ./Mathematik/main.pdf Mathematik.pdf

      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v3
        with:
          name: Mathematik
          path: Mathematik.pdf

      - name: Load Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10' 

      - name: Python FTP Handler
        env:
          FTP_SERVER: ${{ secrets.FTP_SERVER }}
          FTP_PWD: ${{ secrets.FTP_PWD }}
          FTP_USER: ${{ secrets.FTP_USER }}
        run: python upload.py Mathematik.pdf


      - name: Git Clean
        run: git clean -fX
      
      - name: Status
        run: echo "This job's status is ${{ job.status }}."